eljpr/paws

app/models/chat.rb, app/models/dog.rb, app/models/log.rb, app/models/message.rb, app/models/prescription.rb, app/models/vet_dog.rb, app/models/walk.rb, db/migrate/20240513154855_add_first_name_to_users.rb, db/migrate/20240513154910_add_last_name_to_users.rb, db/migrate/20240513155105_add_address_to_users.rb, db/migrate/20240513155122_add_mobile_number_to_users.rb, db/migrate/20240513155614_add_is_vet_to_users.rb, db/migrate/20240513160341_add_opening_time_to_users.rb, db/migrate/20240513160350_add_closing_time_to_users.rb, db/migrate/20240513160741_create_dogs.rb, db/migrate/20240513160949_create_vet_dogs.rb, db/migrate/20240513161058_create_chats.rb, db/migrate/20240513161109_create_messages.rb, db/migrate/20240513161456_create_prescriptions.rb, db/migrate/20240513163631_create_walks.rb, db/migrate/20240513164111_create_logs.rb, db/migrate/20240513165627_add_log_date_to_logs.rb, db/schema.rb, test/models/chat_test.rb, test/models/dog_test.rb, test/models/log_test.rb, test/models/message_test.rb, test/models/prescription_test.rb, test/models/vet_dog_test.rb, test/models/walk_test.rb
created models for: 
users 
dogs 
chats 
messages 
prescriptions
walks
logs 
vet_dogs
=> Creating models

db/migrate/20240513154910_add_last_name_to_users.rb
Updating the column name of the migration from :first_name to :last_name
=> Updating the column name of the migration

db/migrate/20240513163631_create_walks.rb
updating syntax format to precision and scale
=> updating syntax format to precision and scale

db/schema.rb
=> creating column for user

app/assets/stylesheets/config/_colors.scss
Defining variables for our color scheme
=> Defining variables for our color scheme

Gemfile, Gemfile.lock, app/controllers/dogs_controller.rb, app/models/dog.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/dogs/index.html.erb, app/views/dogs/new.html.erb, app/views/dogs/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20240516132113_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
RUN BUNDLE INSTALL 
RUN RAILS DB MIGRATE
RUN RAILS DB SEED
=> added photos to seed

app/controllers/logs_controller.rb
=> Creating the log controller

app/controllers/users_controller.rb, app/controllers/vet_dogs_controller.rb, app/views/dogs/show.html.erb, app/views/layouts/application.html.erb, app/views/users/_vet_details.html.erb, config/routes.rb
=> Vetdog link

app/assets/stylesheets/card_for_owners.scss, app/assets/stylesheets/card_for_vets.scss, app/assets/stylesheets/dog_edit.scss, app/assets/stylesheets/dog_index.scss, app/assets/stylesheets/dog_new.scss, app/assets/stylesheets/dog_show.scss, app/assets/stylesheets/owner_details.scss, app/assets/stylesheets/vet_details.scss, app/views/dogs/_owner_show.html.erb, app/views/dogs/edit.html.erb, app/views/dogs/index.html.erb, app/views/dogs/new.html.erb, app/views/dogs/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/users/_cards_for_owners.erb, app/views/users/_owner_details.html.erb, app/views/users/_vet_details.html.erb
=> More frontend

app/controllers/logs_controller.rb, app/models/log.rb, app/views/logs/edit.html.erb, app/views/logs/index.html.erb, app/views/logs/new.html.erb, app/views/logs/show.html.erb
Creating all the view actions for Logs
=> Creating log views

app/assets/stylesheets/logs/_log_index.scss, app/views/logs/index.html.erb
Fixing issues for elements coloring
=> Fixing issues for elements coloring

app/assets/stylesheets/application.scss, app/assets/stylesheets/logs/_log_index.scss, app/assets/stylesheets/logs/_log_show.scss, app/controllers/logs_controller.rb, app/models/log.rb, app/views/logs/index.html.erb, app/views/logs/show.html.erb, db/migrate/20240521140642_change_columns_to_an_array_in_log.rb, db/schema.rb
Fixing issues for log page. Save, update and layout.
=> Fixing issues for log page. Save, update and layout.

app/assets/stylesheets/logs/_log_edit.scss, app/assets/stylesheets/logs/_log_new.scss, app/models/log.rb
Adding icons to checkboxes on log page
=> Adding icons to checkboxes on log page

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/chats/_chat_index.scss, app/assets/stylesheets/chats/_chat_new.scss, app/assets/stylesheets/chats/_chat_show.scss, app/assets/stylesheets/chats/_index.scss, app/controllers/chats_controller.rb, app/controllers/logs_controller.rb, app/controllers/messages_controller.rb, app/views/chats/index.html.erb, app/views/chats/new.html.erb, app/views/chats/show.html.erb, config/initializers/openai.rb, config/routes.rb, db/migrate/20240522110730_add_content_to_message.rb, db/migrate/20240522162116_add_question_to_message.rb, db/schema.rb
=> Creating Chatbox feature

app/controllers/chats_controller.rb, db/schema.rb
Fixing one issue in the chat controller
=> Fixing one issue in the chat controller

app/controllers/chats_controller.rb
=> Fixing issue on chatbox

app/controllers/chats_controller.rb
Fixing one issue with the chat instance on the index page
=> Fixing one issue with the chat instance on the index page

app/assets/stylesheets/chats/_chat_index.scss, app/assets/stylesheets/chats/_chat_new.scss, app/javascript/controllers/toggle_controller.js, app/views/chats/_answer_chatbox.html.erb, app/views/chats/index.html.erb, app/views/chats/new.html.erb, app/views/chats/show.html.erb
=> Fixing some CSS issues

app/assets/stylesheets/dogs/_dog_index.scss, app/assets/stylesheets/logs/_log_index.scss, app/assets/stylesheets/users/_card_for_owners.scss, app/assets/stylesheets/users/_card_for_vets.scss, app/views/dogs/index.html.erb, app/views/logs/_owner_add_log.html.erb, app/views/logs/index.html.erb, app/views/users/_cards_for_owners.erb, app/views/users/_cards_for_vets.erb
=> Changes on styles

app/assets/stylesheets/chats/_chat_index.scss, app/assets/stylesheets/chats/_chat_new.scss, app/assets/stylesheets/dogs/_dog_index.scss, app/assets/stylesheets/logs/_log_index.scss, app/views/dogs/index.html.erb
=> Final style
